# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_window_length <- function(d) {
    .Call('_kmer_get_window_length', PACKAGE = 'kmer', d)
}

countt_kmers_str <- function(s, d, alphabet, pos) {
    .Call('_kmer_countt_kmers_str', PACKAGE = 'kmer', s, d, alphabet, pos)
}

countt_kmers_num <- function(s, d, alphabet, pos) {
    .Call('_kmer_countt_kmers_num', PACKAGE = 'kmer', s, d, alphabet, pos)
}

