# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

map_up_to_k <- function(sequence, k) {
    .Call('_kmer_map_up_to_k', PACKAGE = 'kmer', sequence, k)
}

map <- function(sequence, k) {
    .Call('_kmer_map', PACKAGE = 'kmer', sequence, k)
}

reduce <- function(l) {
    .Call('_kmer_reduce', PACKAGE = 'kmer', l)
}

map_reduce <- function(sequence, k) {
    .Call('_kmer_map_reduce', PACKAGE = 'kmer', sequence, k)
}

